const DummyMenus = [
  {
    id: 1,
    menuLabelId: "Home",
    label: "Home",
    icon: "home",
    link: "/#",
    status: 1,
    sequence: 1,
    subItems: false,
  },
  {
    id: 2,
    menuLabelId: "SystemConfiguration",
    label: "System Configuration",
    icon: "settings",
    link: "/#",
    status: 1,
    sequence: 1,
    subItems: [
      {
        id: 1,
        submenuLabelId: "Users",
        label: "Users",
        parentId: "SystemConfiguration",
        link: "/users",
        status: 1,
        menuId: 1,
      },
      {
        id: 2,
        submenuLabelId: "ACLRules",
        label: "ACL Rules",
        parentId: "SystemConfiguration",
        link: "/acl-rules",
        status: 1,
        menuId: 1,
      },
    ],
  },
  {
    id: 3,
    menuLabelId: "CampaignManagement",
    label: "Campaign Management",
    icon: "folder",
    status: 1,
    sequence: 2,
    subItems: [
      {
        id: 3,
        submenuLabelId: "Campaign",
        label: "Campaign",
        parentId: "CampaignManagement",
        link: "/campaign",
        status: 1,
        menuId: 2,
      },
      {
        id: 4,
        submenuLabelId: "CRMConfiguration",
        label: "CRM Configuration",
        parentId: "CampaignManagement",
        link: "/crm-configuration",
        status: 1,
        menuId: 2,
      },
      {
        id: 5,
        submenuLabelId: "Mapping",
        parentId: "CampaignManagement",
        label: "Mapping",
        link: "/mapping",
        status: 1,
        menuId: 2,
      },
      {
        id: 6,
        submenuLabelId: "CampaignTransferMapping",
        parentId: "CampaignManagement",
        label: "Campaign Transfer Mapping",
        link: "/campaign-transfer-mapping",
        status: 1,
        menuId: 2,
      },
    ],
  },
];

export default DummyMenus;
